name: spReticle-build

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  # This allows you to run this workflow manually from the GitHub "Actions" tab
  workflow_dispatch:

jobs:
  maya-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
       include:
         - maya: "2019.3"
           devkit: "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN%20Extranet/M%26E/Maya/devkit%202019/Autodesk_Maya_2019_3_Update_DEVKIT_Linux.tgz"
         - maya: "2020.4"
           devkit: "https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN%20Extranet/M%26E/Maya/devkit%202020/Autodesk_Maya_2020_4_Update_DEVKIT_Linux.tgz"

    container: centos:7

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Build Environment
        run: |
          yum-config-manager --add-repo=http://vault.centos.org/7.6.1810/sclo/x86_64/rh/
          yum install mesa-libGL-devel mesa-libGLU-devel wget cmake devtoolset-6 bc -y --nogpgcheck

      - name: Devkit source
        run: |
          echo "Downloading ${{ matrix.devkit }}.."
          wget ${{ matrix.devkit }} -O "$(pwd)/devkit.tgz"
          echo "Extracting devkit.tgz.."
          tar -xvf $(pwd)/devkit.tgz $pwd
          ls

      # For the weird scl_source call below, see:
      # https://github.com/actions/virtual-environments/issues/1279
      - name: Build
        run: |
          . scl_source enable devtoolset-6 || true
          export DEVKIT_LOCATION=$(pwd)/devkitBase
          g++ --version
          mkdir build
          cd build
          EVKIT_LOCATION=$(pwd)/devkitBase cmake ..
          cmake --build . --config Release --target install

      - name: Create distribution
        run: zip -r spReticle_linux_${{matrix.maya}}.zip ./install/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: spReticle_linux_${{matrix.maya}}.zip
